import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageSwitch from "@/components/LanguageSwitch";
import LocalizedLink from "@/components/LocalizedLink";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen bg-white text-gray-900">
          <header className="p-6 border-b flex justify-between items-center shadow-sm">
            <LocalizedLink
              href="/"
              className="flex items-center relative space-x-2"
            >
              <Image
                src={"/logo.png"}
                width={50}
                height={50}
                alt="Logo Yoshimyra"
              />
              <h1 className="text-2xl font-bold">Yoshimyra</h1>
            </LocalizedLink>

            <nav className="space-x-4">
              <LocalizedLink href="/pricing" className="hover:underline">
                Pricing
              </LocalizedLink>
              <LocalizedLink href="/products" className="hover:underline">
                Products
              </LocalizedLink>
              <LocalizedLink
                href="/terms-of-service"
                className="hover:underline"
              >
                Terms
              </LocalizedLink>
              <LocalizedLink href="/contact" className="hover:underline">
                Contact
              </LocalizedLink>
              <LanguageSwitch />
            </nav>
          </header>
          {children}

          <footer className="py-6 border-t text-center text-sm text-gray-500 bg-white">
            © {new Date().getFullYear()} Yoshimyra. All rights reserved.
          </footer>
        </main>
      </body>
    </html>
  );
}
